# This rule is not used by the project reloader-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the reloader.stakater.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: reloader-operator
    app.kubernetes.io/managed-by: kustomize
  name: reloaderconfig-editor-role
rules:
- apiGroups:
  - reloader.stakater.com
  resources:
  - reloaderconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reloader.stakater.com
  resources:
  - reloaderconfigs/status
  verbs:
  - get
