# This rule is not used by the project reloader-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to reloader.stakater.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: reloader-operator
    app.kubernetes.io/managed-by: kustomize
  name: reloaderconfig-viewer-role
rules:
- apiGroups:
  - reloader.stakater.com
  resources:
  - reloaderconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - reloader.stakater.com
  resources:
  - reloaderconfigs/status
  verbs:
  - get
