{{- if and .Values.rbac.create .Values.operator.leaderElection.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "reloader-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reloader-operator.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "reloader-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "reloader-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
