apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "reloader-operator.fullname" . }}-reloaderconfig-editor-role
  labels:
  {{- include "reloader-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - reloader.stakater.com
  resources:
  - reloaderconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - reloader.stakater.com
  resources:
  - reloaderconfigs/status
  verbs:
  - get
