{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reloader-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reloader-operator.labels" . | nindent 4 }}
    control-plane: controller-manager
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.service.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "reloader-operator.selectorLabels" . | nindent 4 }}
    control-plane: controller-manager
{{- end }}
